# This is a demo program that incorporates the lib.
from secure_config import secure_config
from password import sys_pas




config_file="appconfig.conf"
program_pass=sys_pas #in this case the password is imported from a different file. 
#This could be randomly generated by a setup.py and then the whole souce code compiled (maybe with pyinstaller)
sc=secure_config()

###generating the secure file with random key

#sc.generate(config_file,7,program_pass,"FT",print_data=False)
#exit()

####or with a setup generating it with a user-picked password, or a custom key:

#print("Choose an activation / reactivation password for your program: ")
#key=input("Enter password: ")
#sc.generate(config_file,program_pass,"FT",print_data=False,key=key)
#exit()

#the normally used program

cnf=sc.read_file(config_file,program_pass) #read the file
if cnf==False: #if the file is not active there will be a false
    stat=sc.check_status(config_file,program_pass)  #checks the status of the file to see what is the error from
    if stat=="inactive":  #asks activation if inactive
        print("Please activate the program.")
        key=input("Activation Key: ")
        cnf=sc.activate(config_file,program_pass,key)
        if cnf==True: #starts the first configuration of the program
            print("The activation was succesful!")
            login=input("Set your login pass: ")
            message=input("Enter your secret message: ")
            cnt=[login,message]
            sc.write_file(config_file,program_pass,cnt)
        elif cnf==False: #handles a failed activation 
            print("The activation failed.")
    elif stat=="disabled": #asks reactivation if file is disabled
        print("The file is disabled due to tampering. Please reactivate.")
        key=input("Activation Key: ")
        cnf=sc.activate(config_file,program_pass,key)
        if cnf==True:
            print("The reactivation was succesful!")
    elif stat=="corrupted": #informs about the irreversable corruption of the file
        print("The file is irreversibly locked. You can erase it and get a new activation file and key")


else: #the program starts successfully and the active file's content is read and returned
    login=input("Enter your login pass: ")
    while login!=cnf[0]:
        print("Wrong Password")
        login=input("Enter your login pass: ")
    if login==cnf[0]:
        print("Login was successful!")
        cmd=None
        while cmd!= "exit":
            print(cnf[1])
            print("commands: edit, exit, pas")
            cmd=input(">> ")
            if cmd=="edit":
                msg=input("Enter new message: ")
                cnf=[cnf[0],msg]
                sc.write_file(config_file,program_pass,cnf) #edit the file
            elif cmd=="pas":
                pas=input("Enter new password: ")
                cnf=[pas,cnf[1]]
                sc.write_file(config_file,program_pass,cnf) #edit the file
            elif cmd=="exit":
                pass
            else:
                print("Invalid command:")

